"""Render a DocumentContent into a DOCX using the Jinja-instrumented template.

Usage:
    from docx_builder.render import render
    render('output/template_jinja.docx', doc_content, 'output/output.docx',
           image_base='output')

Requires:  pip install docxtpl python-docx lxml
"""
from __future__ import annotations
import collections
import copy
import os
import re
import subprocess
import tempfile
from pathlib import Path

_RE_HAS_INLINE_MATH = re.compile(r'\$[^$\n]+\$')
_RE_SECREF_CELL = re.compile(r':ref\{([^}]+)\}:')

from docx import Document  # type: ignore
from docx.shared import Cm  # type: ignore
from docxtpl import DocxTemplate, InlineImage, RichText  # type: ignore
from lxml import etree  # type: ignore

from .schema import ContentNode, Run, finalize_content

# XML namespace URIs used in image post-processing
_NS_W  = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
_NS_WP = 'http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing'
_NS_A  = 'http://schemas.openxmlformats.org/drawingml/2006/main'


# ---------------------------------------------------------------------------
# Run list → RichText
# ---------------------------------------------------------------------------

def _to_rt(runs: list[Run]) -> RichText:
    rt = RichText()
    for run in runs:
        kwargs = dict(bold=run.bold, italic=run.italic)
        if run.code:
            kwargs['font'] = 'Courier New'
        if run.color:
            kwargs['color'] = run.color
        rt.add(run.text, **kwargs)
    return rt


def _to_text(runs: list[Run]) -> str:
    return ''.join(r.text for r in runs)


def _runs_with_section_label(node: ContentNode) -> list[Run]:
    """Return node runs, appending heading section-label sentinel when present."""
    out = list(node.runs)
    if node.sec_id:
        out.append(Run(text=f'@@SECLABEL:{node.sec_id}@@'))
    return out


# ---------------------------------------------------------------------------
# Proxy classes — wrap ContentNode instances for Jinja template access
# ---------------------------------------------------------------------------

class HeadingProxy:
    """Proxy for h1–h4, paragraph, and bullet nodes.

    NOTE: docxtpl RichText objects do not render inside {%p if %} blocks.
    We therefore render a unique placeholder string and restore formatted runs
    in _post_process_inline_runs().
    """

    def __init__(
        self,
        node: ContentNode,
        math_counter: int = 0,
        text_placeholder: str | None = None,
    ) -> None:
        self._node = node
        self.type = node.type
        self._math_counter = math_counter
        self._text_placeholder = text_placeholder

    @property
    def text(self) -> str:
        if self._text_placeholder:
            return self._text_placeholder
        t = _to_text(self._node.runs)
        if self._node.sec_id:
            t += f'@@SECLABEL:{self._node.sec_id}@@'
        return t

    @property
    def has_math(self) -> bool:
        return self._node.has_math

    @property
    def math_placeholder(self) -> str:
        return f'MATH_PARA_{self._math_counter}'


class BulletProxy(HeadingProxy):
    """Same as HeadingProxy; bullet style is applied by the template paragraph."""
    @property
    def level(self) -> int:
        return self._node.level


class MathDisplayProxy:
    """Proxy for display math nodes ($$...$$).

    Renders a sentinel string in the template; _post_process_math() replaces it
    with the actual OMML paragraph generated by pandoc.
    """

    def __init__(self, node: ContentNode, counter: int) -> None:
        self._node = node
        self.type = 'math_display'
        self.math_placeholder = f'MATH_DISP_{counter}'

    # has_math is not needed for display math nodes, but keep interface consistent
    has_math: bool = False


class FigureProxy:
    """Proxy for figure nodes.

    Attributes used in the template:
      item.type         — 'figure'
      item.fig_number   — sequential figure number
      item.image        — InlineImage (or placeholder RichText)
      item.title        — plain string  "Figure N: Short Title"  (bold label)
      item.caption      — plain string  detailed description paragraph
      item.caption_text — plain string for LOF entries (short title only)
    """

    def __init__(self, node: ContentNode, tpl: DocxTemplate, image_base: Path, text_width: int) -> None:
        self._node = node
        self._tpl = tpl
        self._image_base = image_base
        self.type = 'figure'
        self._text_width = text_width
        self.fig_number = node.fig_number
        # LOF uses the short title, not the long description
        self.caption_text = _to_text(node.fig_title) or _to_text(node.fig_caption)
        # Cache caption text and detect inline math for post-processing
        self._caption_text = _to_text(node.fig_caption)
        self.has_caption_math = bool(_RE_HAS_INLINE_MATH.search(self._caption_text)) if self._caption_text else False
        self.caption_math_placeholder = f'MATH_CAP_{node.fig_number}' if self.has_caption_math else ''

    def _resolve_width(self) -> int:
        """Return image width in EMU from fig_width_hint, or full text width."""
        hint = self._node.fig_width_hint
        if not hint:
            return self._text_width
        if hint.endswith('%'):
            try:
                pct = float(hint[:-1])
                return int(self._text_width * pct / 100)
            except ValueError:
                return self._text_width
        if hint.endswith('cm'):
            try:
                cm = float(hint[:-2])
                return Cm(cm)
            except ValueError:
                return self._text_width
        return self._text_width

    @property
    def image(self) -> InlineImage | RichText:
        path = self._node.fig_path
        if not path:
            return RichText(f'[Figure {self.fig_number}: no image]', italic=True)

        width = self._resolve_width()

        if path.startswith('_mermaid:'):
            fig_id = path[len('_mermaid:'):]
            # Look for a pre-rendered PNG next to the draft
            for candidate in [
                self._image_base / f'{fig_id}.png',
                self._image_base / 'figures' / f'{fig_id}.png',
                self._image_base / 'snaps' / f'{fig_id}.png',
            ]:
                if candidate.exists():
                    return InlineImage(self._tpl, str(candidate), width=width)
            return RichText(
                f'[Figure {self.fig_number}: Mermaid diagram — run mmdc to render {fig_id}.png]',
                italic=True,
            )

        # Resolve relative path
        full = Path(path) if Path(path).is_absolute() else self._image_base / path
        if full.exists():
            return InlineImage(self._tpl, str(full), width=width)
        return RichText(f'[Figure {self.fig_number}: {path} not found]', italic=True)

    @property
    def title(self) -> str:
        """Short label: 'Figure N: Short Title' — shown above the image."""
        short = _to_text(self._node.fig_title)
        return f'Figure {self.fig_number}: {short}' if short else ''

    @property
    def caption(self) -> RichText | str:
        """Detailed description — italic text only, shown below the figure-title label.

        When the caption contains inline math, returns a sentinel string
        (MATH_CAP_N) that _post_process_math() will replace with OMML.
        """
        if self.has_caption_math:
            return self.caption_math_placeholder
        if not self._caption_text:
            return RichText('')
        rt = RichText()
        rt.add(self._caption_text, italic=True)
        return rt

    @property
    def fig_start(self) -> str:
        return f'FIGURE_START_{self.fig_number}'

    @property
    def fig_end(self) -> str:
        return f'FIGURE_END_{self.fig_number}'


class TableProxy:
    """Proxy for table nodes.

    Attributes used in the template:
      item.type         — 'table'
      item.tbl_number   — sequential table number
      item.caption      — RichText  "Table N: caption text"
      item.caption_text — plain string for LOT entries
      item.subdoc       — SubDocxTemplate containing the rendered table
    """

    def __init__(self, node: ContentNode, tpl: DocxTemplate) -> None:
        self._node = node
        self._tpl = tpl
        self.type = 'table'
        self.tbl_number = node.tbl_number
        self.caption_text = _to_text(node.tbl_caption)

    @property
    def caption(self) -> str:
        return f'Table {self.tbl_number}: {_to_text(self._node.tbl_caption)}'

    @property
    def subdoc(self) -> str:
        """Return a unique placeholder string.

        Subdocs inside {%p if %} blocks do not work with docxtpl.
        We use a sentinel string; _post_process_tables() replaces it with
        the actual table after docxtpl rendering.
        """
        return f'TABLE_PLACEHOLDER_{self.tbl_number}'


# ---------------------------------------------------------------------------
# Proxy factory
# ---------------------------------------------------------------------------

def _build_content_proxies(
    content: list[ContentNode],
    tpl: DocxTemplate,
    image_base: Path,
    text_width: int,
) -> tuple[list, dict[str, list[Run]]]:
    """Build proxy list, assigning sequential math counters."""
    proxies = []
    inline_map: dict[str, list[Run]] = {}
    math_disp_n = 0
    math_para_n = 0
    inline_n = 0
    for node in content:
        if node.type == 'figure':
            proxies.append(FigureProxy(node, tpl, image_base, text_width))
        elif node.type == 'table':
            proxies.append(TableProxy(node, tpl))
        elif node.type == 'math_display':
            math_disp_n += 1
            proxies.append(MathDisplayProxy(node, math_disp_n))
        elif node.type == 'bullet' and node.has_math:
            math_para_n += 1
            proxies.append(BulletProxy(node, math_para_n))
        elif node.type in {'p', 'numbered'} and node.has_math:
            math_para_n += 1
            proxies.append(HeadingProxy(node, math_counter=math_para_n))
        elif node.type in {'h1', 'h2', 'h3', 'h4', 'p', 'numbered'}:
            inline_n += 1
            key = f'@@INLINEFMT:{inline_n}@@'
            inline_map[key] = _runs_with_section_label(node)
            proxies.append(HeadingProxy(node, text_placeholder=key))
        elif node.type == 'bullet':
            inline_n += 1
            key = f'@@INLINEFMT:{inline_n}@@'
            inline_map[key] = _runs_with_section_label(node)
            proxies.append(BulletProxy(node, text_placeholder=key))
        else:
            proxies.append(HeadingProxy(node))
    return proxies, inline_map


def _post_process_inline_runs(docx_path: str, inline_map: dict[str, list[Run]]) -> None:
    """Replace inline-format placeholders with explicit formatted Word runs."""
    if not inline_map:
        return

    from docx import Document as DocxDoc
    from docx.oxml import OxmlElement

    W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
    XML_SPACE = '{http://www.w3.org/XML/1998/namespace}space'

    def _set_bold(r_pr):
        for tag in ('b', 'bCs'):
            if r_pr.find(f'{{{W}}}{tag}') is None:
                r_pr.append(OxmlElement(f'w:{tag}'))

    def _set_italic(r_pr):
        for tag in ('i', 'iCs'):
            if r_pr.find(f'{{{W}}}{tag}') is None:
                r_pr.append(OxmlElement(f'w:{tag}'))

    def _set_color(r_pr, color_val):
        color_el = OxmlElement('w:color')
        # Normalize: ensure hex colors have no '#' prefix for OOXML
        val = color_val.lstrip('#')
        color_el.set(f'{{{W}}}val', val)
        if r_pr.find(f'{{{W}}}color') is None:
            r_pr.append(color_el)

    def _append_run(p_el, run: Run):
        if not run.text:
            return
        r_el = OxmlElement('w:r')
        if run.bold or run.italic or run.code or run.color:
            r_pr = OxmlElement('w:rPr')
            if run.bold:
                _set_bold(r_pr)
            if run.italic:
                _set_italic(r_pr)
            if run.code:
                fonts_el = OxmlElement('w:rFonts')
                fonts_el.set(f'{{{W}}}ascii', 'Courier New')
                fonts_el.set(f'{{{W}}}hAnsi', 'Courier New')
                r_pr.append(fonts_el)
            if run.color:
                _set_color(r_pr, run.color)
            r_el.append(r_pr)
        t_el = OxmlElement('w:t')
        t_el.set(XML_SPACE, 'preserve')
        t_el.text = run.text
        r_el.append(t_el)
        p_el.append(r_el)

    doc = DocxDoc(docx_path)
    replaced = 0

    all_paras = list(doc.paragraphs)
    for tbl in doc.tables:
        for row in tbl.rows:
            for cell in row.cells:
                all_paras.extend(cell.paragraphs)

    for para in all_paras:
        key = para.text.strip()
        runs = inline_map.get(key)
        if runs is None:
            continue

        p_el = para._p
        for r in list(p_el.findall(f'{{{W}}}r')):
            p_el.remove(r)

        for run in runs:
            _append_run(p_el, run)

        replaced += 1

    if replaced:
        doc.save(docx_path)
        print(f'Post-processed {replaced} inline-formatted paragraph(s) in {docx_path}')


# ---------------------------------------------------------------------------
# Public render function
# ---------------------------------------------------------------------------

def _post_process_tables(docx_path: str, tables_list: list[ContentNode]) -> None:
    """Replace TABLE_PLACEHOLDER_N paragraphs with actual python-docx tables."""
    from docx import Document as DocxDocument
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    doc = DocxDocument(docx_path)

    # Build a lookup: tbl_number → ContentNode
    tbl_map = {n.tbl_number: n for n in tables_list}

    replaced = 0
    for para in list(doc.paragraphs):
        txt = para.text.strip()
        if not txt.startswith('TABLE_PLACEHOLDER_'):
            continue
        try:
            tbl_num = int(txt.split('TABLE_PLACEHOLDER_')[1])
        except (IndexError, ValueError):
            continue
        node = tbl_map.get(tbl_num)
        if node is None:
            continue

        headers = node.tbl_headers
        rows = node.tbl_rows
        if not headers:
            continue
        n_cols = len(headers)
        n_rows = 1 + len(rows)

        # Build the table (appended to end initially)
        tbl = doc.add_table(rows=n_rows, cols=n_cols, style='Table Grid')

        # Header row — bold
        for ci, hdr in enumerate(headers):
            cell = tbl.rows[0].cells[ci]
            cell.text = hdr
            for run in cell.paragraphs[0].runs:
                run.bold = True

        # Data rows
        for ri, row_data in enumerate(rows):
            for ci, val in enumerate(row_data[:n_cols]):
                val = _RE_SECREF_CELL.sub(lambda m: f'@@SECREF:{m.group(1)}@@', val)
                tbl.rows[ri + 1].cells[ci].text = val

        # Move table to immediately after the placeholder paragraph
        para._p.addnext(tbl._tbl)

        # Remove placeholder paragraph
        para._p.getparent().remove(para._p)
        replaced += 1

    if replaced:
        doc.save(docx_path)
        print(f'Post-processed {replaced} table(s) into {docx_path}')


def _post_process_math(docx_path: str, content_proxies: list) -> None:
    """Replace MATH_DISP_N / MATH_PARA_N sentinels with OMML paragraphs via pandoc."""
    from docx import Document as DocxDoc

    # Build sentinel → (latex_src, is_display, italic) map
    math_map: dict[str, tuple[str, bool, bool]] = {}
    for proxy in content_proxies:
        if isinstance(proxy, MathDisplayProxy):
            math_map[proxy.math_placeholder] = (proxy._node.math_src, True, False)
        elif isinstance(proxy, HeadingProxy) and proxy.has_math:
            math_map[proxy.math_placeholder] = (proxy._node.math_raw, False, False)
        elif isinstance(proxy, FigureProxy) and proxy.has_caption_math:
            math_map[proxy.caption_math_placeholder] = (proxy._caption_text, False, True)

    if not math_map:
        return

    def _pandoc_to_para(src: str, display: bool):
        """Convert LaTeX math (display or inline paragraph) to an OMML lxml element."""
        md = f'$$\n{src}\n$$\n' if display else src + '\n'
        with tempfile.NamedTemporaryFile(suffix='.docx', delete=False) as f:
            tmp = f.name
        try:
            result = subprocess.run(
                ['pandoc', '-f', 'markdown+tex_math_dollars', '-t', 'docx', '-o', tmp],
                input=md.encode('utf-8'),
                capture_output=True,
            )
            if result.returncode != 0:
                return None
            tmp_doc = DocxDoc(tmp)
            OMML_NS = 'http://schemas.openxmlformats.org/officeDocument/2006/math'
            for para in tmp_doc.paragraphs:
                if para._p.find(f'.//{{{OMML_NS}}}oMath') is not None or para.text.strip():
                    return para._p
            return None
        except Exception as exc:
            print(f'  [math] pandoc error: {exc}')
            return None
        finally:
            try:
                os.unlink(tmp)
            except OSError:
                pass

    NS_W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'

    doc = DocxDoc(docx_path)
    replaced = 0
    # Use iter() so paragraphs inside table cells are also found.
    all_para_els = [el for el in doc.element.body.iter()
                    if el.tag == f'{{{NS_W}}}p']
    for p_el in all_para_els:
        txt = ''.join(t.text or '' for t in p_el.findall(f'.//{{{NS_W}}}t')).strip()
        if txt not in math_map:
            continue
        src, display, italic = math_map[txt]
        new_p = _pandoc_to_para(src, display)
        if new_p is not None:
            # Apply italic to all text runs when the source is a figure caption.
            if italic:
                for r_el in new_p.findall(f'.//{{{NS_W}}}r'):
                    rPr = r_el.find(f'{{{NS_W}}}rPr')
                    if rPr is None:
                        rPr = etree.Element(f'{{{NS_W}}}rPr')
                        r_el.insert(0, rPr)
                    if rPr.find(f'{{{NS_W}}}i') is None:
                        etree.SubElement(rPr, f'{{{NS_W}}}i')
                    if rPr.find(f'{{{NS_W}}}iCs') is None:
                        etree.SubElement(rPr, f'{{{NS_W}}}iCs')
            # Copy paragraph properties (style, bullet numbering, indent) from
            # the placeholder paragraph so bullet/para formatting is preserved.
            orig_pPr = p_el.find(f'{{{NS_W}}}pPr')
            if orig_pPr is not None:
                new_pPr = new_p.find(f'{{{NS_W}}}pPr')
                orig_copy = copy.deepcopy(orig_pPr)
                if new_pPr is not None:
                    new_p.replace(new_pPr, orig_copy)
                else:
                    new_p.insert(0, orig_copy)
            p_el.addnext(new_p)
            p_el.getparent().remove(p_el)
            replaced += 1
        else:
            print(f'  [math] WARNING: failed to convert "{txt[:60]}"')

    if replaced:
        doc.save(docx_path)
        print(f'Post-processed {replaced} math expression(s) into {docx_path}')


def _inline_to_anchor(inline_el) -> None:
    """Convert a <wp:inline> element in-place to <wp:anchor> with Top-and-Bottom wrapping.

    Modifies the element's tag and attributes, inserts the required positional
    child elements, and adds <wp:wrapTopAndBottom/>.  The graphic payload
    (extent, effectExtent, docPr, cNvGraphicFramePr, a:graphic) is preserved.
    """
    WP = _NS_WP

    # Change tag from wp:inline → wp:anchor
    inline_el.tag = f'{{{WP}}}anchor'

    # Required anchor attributes (inline has distT/distB/distL/distR already
    # but lacks the rest)
    inline_el.set('simplePos', '0')
    inline_el.set('relativeHeight', '251658240')
    inline_el.set('behindDoc', '0')
    inline_el.set('locked', '0')
    inline_el.set('layoutInCell', '1')
    inline_el.set('allowOverlap', '0')
    for dist in ('distT', 'distB', 'distL', 'distR'):
        if inline_el.get(dist) is None:
            inline_el.set(dist, '0')

    # Build positional elements to insert at the front (before wp:extent)
    simple_pos = etree.Element(f'{{{WP}}}simplePos')
    simple_pos.set('x', '0')
    simple_pos.set('y', '0')

    pos_h = etree.Element(f'{{{WP}}}positionH')
    pos_h.set('relativeFrom', 'column')
    align_h = etree.SubElement(pos_h, f'{{{WP}}}align')
    align_h.text = 'center'

    pos_v = etree.Element(f'{{{WP}}}positionV')
    pos_v.set('relativeFrom', 'paragraph')
    align_v = etree.SubElement(pos_v, f'{{{WP}}}align')
    align_v.text = 'top'

    # Insert positional elements before the first child (wp:extent)
    extent_el = inline_el.find(f'{{{WP}}}extent')
    idx = list(inline_el).index(extent_el) if extent_el is not None else 0
    for i, el in enumerate([simple_pos, pos_h, pos_v]):
        inline_el.insert(idx + i, el)

    # Insert <wp:wrapTopAndBottom/> after wp:extent (and wp:effectExtent if present)
    effect_el = inline_el.find(f'{{{WP}}}effectExtent')
    anchor_child = effect_el if effect_el is not None else inline_el.find(f'{{{WP}}}extent')
    if anchor_child is not None:
        wrap_el = etree.Element(f'{{{WP}}}wrapTopAndBottom')
        anchor_child.addnext(wrap_el)
    else:
        inline_el.append(etree.Element(f'{{{WP}}}wrapTopAndBottom'))


_RE_SECLABEL = re.compile(r'@@SECLABEL:([^@]+)@@')
_RE_SECREF_SENT = re.compile(r'@@SECREF:([^@]+)@@')
_RE_FIGREF_SENT = re.compile(r'@@FIGREF:([^@]+)@@')
_RE_TABREF_SENT = re.compile(r'@@TABREF:([^@]+)@@')


def _post_process_figures(docx_path: str, figure_title_style: str = 'FImageTitle') -> None:
    """Wrap each figure block in a no-border 2-row table (image row + caption row).

    Finds FIGURE_START_N / FIGURE_END_N sentinel paragraphs placed by the Jinja
    template, collects the image and caption paragraphs between them, and replaces
    the whole group with a borderless table:

      Row 0  — image (centered, keepNext so it stays with Row 1)
      Row 1  — figure-title paragraph (bold italic) + caption paragraph(s)

    figure_title_style is the template's style ID for figure title paragraphs
    (a RENDER_OPTIONS key exported by the project's template prep script).

    Spacing of 160 twips is added above Row 0 and below the last caption paragraph
    to separate the figure from surrounding body text.  Both rows have cantSplit so
    the table does not break across pages.

    Must run BEFORE _post_process_math so that MATH_CAP_N sentinels, if present
    in the caption paragraph, are still found by doc.paragraphs after being moved
    into the table cell.
    """
    from docx import Document as DocxDoc
    from docx.oxml import OxmlElement

    NS_W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
    NS_WP = 'http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing'

    def _get_text(el):
        return ''.join(t.text or '' for t in el.findall(f'.//{{{NS_W}}}t'))

    def _set_spacing(p_el, before=None, after=None, line=None, line_rule=None):
        pPr = p_el.find(f'{{{NS_W}}}pPr')
        if pPr is None:
            pPr = OxmlElement('w:pPr')
            p_el.insert(0, pPr)
        spacing = pPr.find(f'{{{NS_W}}}spacing')
        if spacing is None:
            spacing = OxmlElement('w:spacing')
            pPr.append(spacing)
        if before is not None:
            spacing.set(f'{{{NS_W}}}before', str(before))
        if after is not None:
            spacing.set(f'{{{NS_W}}}after', str(after))
        if line is not None:
            spacing.set(f'{{{NS_W}}}line', str(line))
        if line_rule is not None:
            spacing.set(f'{{{NS_W}}}lineRule', line_rule)

    def _set_keep_next(p_el):
        pPr = p_el.find(f'{{{NS_W}}}pPr')
        if pPr is None:
            pPr = OxmlElement('w:pPr')
            p_el.insert(0, pPr)
        if pPr.find(f'{{{NS_W}}}keepNext') is None:
            pPr.append(OxmlElement('w:keepNext'))

    def _make_cant_split_tr_pr():
        trPr = OxmlElement('w:trPr')
        cs = OxmlElement('w:cantSplit')
        trPr.append(cs)
        return trPr

    def _make_auto_tc(paras):
        tc = OxmlElement('w:tc')
        tcPr = OxmlElement('w:tcPr')
        tcW = OxmlElement('w:tcW')
        tcW.set(f'{{{NS_W}}}w', '0')
        tcW.set(f'{{{NS_W}}}type', 'auto')
        tcPr.append(tcW)
        tcMar = OxmlElement('w:tcMar')
        for side in ('top', 'left', 'bottom', 'right'):
            m = OxmlElement(f'w:{side}')
            m.set(f'{{{NS_W}}}w', '120')
            m.set(f'{{{NS_W}}}type', 'dxa')
            tcMar.append(m)
        tcPr.append(tcMar)
        tc.append(tcPr)
        for p in paras:
            tc.append(p)
        return tc

    def _build_table(image_paras, caption_paras):
        tbl = OxmlElement('w:tbl')

        # Table properties
        tblPr = OxmlElement('w:tblPr')
        tblW = OxmlElement('w:tblW')
        tblW.set(f'{{{NS_W}}}w', '5000')
        tblW.set(f'{{{NS_W}}}type', 'pct')
        tblPr.append(tblW)
        tblBorders = OxmlElement('w:tblBorders')
        for name in ('top', 'left', 'bottom', 'right', 'insideH', 'insideV'):
            b = OxmlElement(f'w:{name}')
            if name in ('top', 'bottom'):
                b.set(f'{{{NS_W}}}val', 'single')
                b.set(f'{{{NS_W}}}sz', '6')
                b.set(f'{{{NS_W}}}space', '0')
                b.set(f'{{{NS_W}}}color', 'auto')
            else:
                b.set(f'{{{NS_W}}}val', 'none')
                b.set(f'{{{NS_W}}}sz', '0')
                b.set(f'{{{NS_W}}}space', '0')
                b.set(f'{{{NS_W}}}color', 'auto')
            tblBorders.append(b)
        tblPr.append(tblBorders)
        tbl.append(tblPr)

        # Single-column grid
        tblGrid = OxmlElement('w:tblGrid')
        tblGrid.append(OxmlElement('w:gridCol'))
        tbl.append(tblGrid)

        # Row 0: image
        tr0 = OxmlElement('w:tr')
        tr0.append(_make_cant_split_tr_pr())
        tr0.append(_make_auto_tc(image_paras))
        tbl.append(tr0)

        # Row 1: caption (title + long description)
        tr1 = OxmlElement('w:tr')
        tr1.append(_make_cant_split_tr_pr())
        tr1.append(_make_auto_tc(caption_paras))
        tbl.append(tr1)

        return tbl

    doc = DocxDoc(docx_path)
    body = doc.element.body
    found = 0

    while True:
        children = list(body)
        start_el = None
        fig_num = None
        for el in children:
            if el.tag != f'{{{NS_W}}}p':
                continue
            txt = _get_text(el).strip()
            if txt.startswith('FIGURE_START_'):
                try:
                    fig_num = int(txt[len('FIGURE_START_'):])
                    start_el = el
                    break
                except ValueError:
                    continue
        if start_el is None:
            break

        end_sentinel = f'FIGURE_END_{fig_num}'
        content_els = []
        end_el = None
        collecting = False
        for el in children:
            if el is start_el:
                collecting = True
                continue
            if not collecting:
                continue
            if _get_text(el).strip() == end_sentinel:
                end_el = el
                break
            content_els.append(el)

        if end_el is None:
            body.remove(start_el)
            continue

        # Split into image paragraphs vs caption paragraphs
        image_paras, caption_paras = [], []
        for el in content_els:
            if el.tag == f'{{{NS_W}}}p' and (
                el.find(f'.//{{{NS_WP}}}inline') is not None or
                el.find(f'.//{{{NS_WP}}}anchor') is not None
            ):
                image_paras.append(el)
            else:
                caption_paras.append(el)

        # Bold the runs in any figure-title paragraph in the caption cell
        for p in caption_paras:
            if p.tag != f'{{{NS_W}}}p':
                continue
            ps = p.find(f'.//{{{NS_W}}}pStyle')
            if ps is None or ps.get(f'{{{NS_W}}}val') != figure_title_style:
                continue
            for r in p.findall(f'{{{NS_W}}}r'):
                rPr = r.find(f'{{{NS_W}}}rPr')
                if rPr is None:
                    rPr = OxmlElement('w:rPr')
                    r.insert(0, rPr)
                for tag in ('b', 'bCs'):
                    if rPr.find(f'{{{NS_W}}}' + tag) is None:
                        rPr.append(OxmlElement(f'w:{tag}'))

        # Spacing: 160 twips above first image para, zero after each image para so
        # Normal-style paragraph spacing does not bleed into the caption row below.
        # line=1/lineRule=exact collapses the anchor paragraph's own line height to
        # 1 twip so the phantom empty line below the image disappears.
        if image_paras:
            _set_spacing(image_paras[0], before=160, after=0, line=1, line_rule='exact')
            for p in image_paras[1:]:
                _set_spacing(p, after=0, line=1, line_rule='exact')
            for p in image_paras:
                _set_keep_next(p)
        if caption_paras:
            _set_spacing(caption_paras[-1], after=160)

        # Fallback empty paragraphs
        if not image_paras:
            image_paras = [OxmlElement('w:p')]
        if not caption_paras:
            caption_paras = [OxmlElement('w:p')]

        # Detach content elements from body
        for el in content_els:
            body.remove(el)

        # Build table with the detached elements and insert before start sentinel
        tbl = _build_table(image_paras, caption_paras)
        start_el.addprevious(tbl)

        # Remove the two sentinel paragraphs
        body.remove(start_el)
        body.remove(end_el)

        # Insert a zero-height empty paragraph after the table so adjacent
        # figure tables are not merged by Word into a single table.
        spacer = OxmlElement('w:p')
        spacer_pPr = OxmlElement('w:pPr')
        spacer_spacing = OxmlElement('w:spacing')
        spacer_spacing.set(f'{{{NS_W}}}before', '0')
        spacer_spacing.set(f'{{{NS_W}}}after', '0')
        spacer_spacing.set(f'{{{NS_W}}}line', '1')
        spacer_spacing.set(f'{{{NS_W}}}lineRule', 'exact')
        spacer_pPr.append(spacer_spacing)
        spacer.append(spacer_pPr)
        tbl.addnext(spacer)

        found += 1

    if found:
        doc.save(docx_path)
        print(f'Post-processed {found} figure(s) into borderless 2-row tables in {docx_path}')


def _post_process_crossrefs(
    docx_path: str,
    content_nodes: list[ContentNode],
    fig_map: dict[str, int],
    tab_map: dict[str, int],
    figure_title_style: str = 'FImageTitle',
) -> None:
    """Insert Word bookmarks on labelled headings, figure titles, and REF/HYPERLINK fields at cross-reference sites."""
    from docx import Document as DocxDoc
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
    XML_SPACE = '{http://www.w3.org/XML/1998/namespace}space'

    doc = DocxDoc(docx_path)

    # Start bookmark IDs above any already present in the document
    existing_ids = [
        int(bm.get(qn('w:id'), '0'))
        for bm in doc.element.body.findall(f'.//{{{W}}}bookmarkStart')
    ]
    bookmark_counter = [max(existing_ids) + 1 if existing_ids else 0]

    def _safe_bm_name(sec_id: str) -> str:
        """Word bookmark names: letters, digits, underscores only, start with letter."""
        return 'sec_' + re.sub(r'[^A-Za-z0-9_]', '_', sec_id)

    def _safe_fig_bm_name(fig_id: str) -> str:
        """Bookmark name for a figure."""
        return 'fig_' + re.sub(r'[^A-Za-z0-9_]', '_', fig_id)

    def _safe_tab_bm_name(tab_id: str) -> str:
        """Bookmark name for a table."""
        return 'tab_' + re.sub(r'[^A-Za-z0-9_]', '_', tab_id)

    def _fld_run(fld_type: str) -> 'etree._Element':
        r = OxmlElement('w:r')
        fc = OxmlElement('w:fldChar')
        fc.set(qn('w:fldCharType'), fld_type)
        r.append(fc)
        return r

    def _instr_run(instr: str) -> 'etree._Element':
        r = OxmlElement('w:r')
        t = OxmlElement('w:instrText')
        t.set(XML_SPACE, 'preserve')
        t.text = instr
        r.append(t)
        return r

    def _text_run(text: str, source_run: 'etree._Element | None' = None) -> 'etree._Element':
        r = OxmlElement('w:r')
        if source_run is not None:
            src_rpr = source_run.find(f'{{{W}}}rPr')
            if src_rpr is not None:
                r.append(copy.deepcopy(src_rpr))
        t = OxmlElement('w:t')
        t.set(XML_SPACE, 'preserve')
        t.text = text
        r.append(t)
        return r

    replaced_labels = 0
    replaced_refs = 0
    replaced_fig_refs = 0
    replaced_tab_refs = 0

    all_paras = list(doc.paragraphs)
    for tbl in doc.tables:
        for row in tbl.rows:
            for cell in row.cells:
                all_paras.extend(cell.paragraphs)

    # --- Phase 1: Create bookmarks on figure title paragraphs (figure_title_style) ---
    # Use raw XML iteration because figure tables are built with lxml elements
    # that python-docx's doc.tables / doc.paragraphs don't enumerate.
    fig_num_to_id = {v: k for k, v in fig_map.items()}

    all_p_els = list(doc.element.body.iter(f'{{{W}}}p'))

    # --- Phase 0: Repair malformed nested runs (<w:r><w:t><w:r>...</w:r></w:t></w:r>) ---
    # docxtpl renders a RichText caption via plain {{ }} (not {{r }}), nesting the
    # formatted runs inside the placeholder run's <w:t>.  This is invalid OOXML and
    # hides any sentinel inside the nested run from the cross-reference scanner.
    # Lift the nested runs out so they become valid sibling runs of the paragraph.
    for p in all_p_els:
        for outer in list(p.findall(f'{{{W}}}r')):
            t_el = outer.find(f'{{{W}}}t')
            if t_el is None:
                continue
            nested = t_el.findall(f'{{{W}}}r')
            if not nested:
                continue
            outer_rpr = outer.find(f'{{{W}}}rPr')
            new_runs: list['etree._Element'] = []

            def _wrap_text(text: str) -> 'etree._Element':
                r = OxmlElement('w:r')
                if outer_rpr is not None:
                    r.append(copy.deepcopy(outer_rpr))
                t = OxmlElement('w:t')
                t.set(XML_SPACE, 'preserve')
                t.text = text
                r.append(t)
                return r

            if t_el.text:
                new_runs.append(_wrap_text(t_el.text))
            for inner in nested:
                tail = inner.tail
                inner.tail = None
                new_runs.append(inner)
                if tail:
                    new_runs.append(_wrap_text(tail))

            for nr in new_runs:
                outer.addprevious(nr)
            p.remove(outer)

    for p in all_p_els:
        pPr = p.find(f'{{{W}}}pPr')
        ps = pPr.find(f'{{{W}}}pStyle') if pPr is not None else None
        if ps is None or ps.get(f'{{{W}}}val') != figure_title_style:
            continue
        txt = ''.join(t.text or '' for t in p.findall(f'.//{{{W}}}t')).strip()
        m = re.match(r'Figure\s+(\d+)', txt)
        if not m:
            continue
        fig_num = int(m.group(1))
        fig_id = fig_num_to_id.get(fig_num)
        if not fig_id:
            continue
        bm_name = _safe_fig_bm_name(fig_id)
        bid = bookmark_counter[0]
        bookmark_counter[0] += 1

        first_run = p.find(f'{{{W}}}r')
        if first_run is not None:
            bm_start = OxmlElement('w:bookmarkStart')
            bm_start.set(qn('w:id'), str(bid))
            bm_start.set(qn('w:name'), bm_name)
            first_run.addprevious(bm_start)

            bm_end = OxmlElement('w:bookmarkEnd')
            bm_end.set(qn('w:id'), str(bid))
            first_run.addnext(bm_end)

    # --- Phase 1b: Create bookmarks on table caption paragraphs ---
    tab_num_to_id = {v: k for k, v in tab_map.items()}

    for para in all_paras:
        p = para._p
        txt = para.text.strip()
        m = re.match(r'Table\s+(\d+)', txt)
        if not m:
            continue
        tab_num = int(m.group(1))
        tab_id = tab_num_to_id.get(tab_num)
        if not tab_id:
            continue
        bm_name = _safe_tab_bm_name(tab_id)
        bid = bookmark_counter[0]
        bookmark_counter[0] += 1

        first_run = p.find(f'{{{W}}}r')
        if first_run is not None:
            bm_start = OxmlElement('w:bookmarkStart')
            bm_start.set(qn('w:id'), str(bid))
            bm_start.set(qn('w:name'), bm_name)
            first_run.addprevious(bm_start)

            bm_end = OxmlElement('w:bookmarkEnd')
            bm_end.set(qn('w:id'), str(bid))
            first_run.addnext(bm_end)

    # --- Phase 1c: Repair sentinels split across runs by pandoc math rendering ---
    # Pandoc may split @@SECREF:id@@ / @@FIGREF:id@@ / @@TABREF:id@@ across
    # adjacent w:r elements (e.g. @ | @FIGREF:id | @@). A paragraph can contain
    # several such sentinels back-to-back, so keep repairing until none remain.
    _RE_ANY_SENT = re.compile(r'@@(?:SECREF|FIGREF|TABREF):[^@]+@@')
    for para in all_paras:
        p = para._p
        while True:
            runs = list(p.findall(f'{{{W}}}r'))
            segments: list[tuple[int, int, 'etree._Element', str]] = []
            pos = 0
            for r in runs:
                rtext = ''.join(t.text or '' for t in r.findall(f'{{{W}}}t'))
                segments.append((pos, pos + len(rtext), r, rtext))
                pos += len(rtext)
            combined = ''.join(s[3] for s in segments)

            broken = None
            for m in _RE_ANY_SENT.finditer(combined):
                spanning = [s for s in segments if s[0] < m.end() and s[1] > m.start()]
                if len(spanning) > 1:
                    broken = (m, spanning)
                    break
            if broken is None:
                break

            m, spanning = broken
            target_runs = [s[2] for s in spanning]
            merged_text = ''.join(s[3] for s in spanning)
            m2 = _RE_ANY_SENT.search(merged_text)
            if not m2:
                break
            prefix = merged_text[:m2.start()]
            suffix = merged_text[m2.end():]
            # Build replacement runs: prefix (optional), sentinel run, suffix (optional)
            new_runs: list['etree._Element'] = []
            if prefix:
                pr = OxmlElement('w:r')
                pt = OxmlElement('w:t')
                pt.set(XML_SPACE, 'preserve')
                pt.text = prefix
                pr.append(pt)
                new_runs.append(pr)
            sr = copy.deepcopy(target_runs[0])
            for st in sr.findall(f'{{{W}}}t'):
                st.text = m2.group(0)
            new_runs.append(sr)
            if suffix:
                su = OxmlElement('w:r')
                sut = OxmlElement('w:t')
                sut.set(XML_SPACE, 'preserve')
                sut.text = suffix
                su.append(sut)
                new_runs.append(su)
            # Anchor insertion at the run immediately following the split block
            # (positionally correct for mid-paragraph splits, not just paragraph-initial ones).
            last_target_idx = max(runs.index(r) for r in target_runs)
            next_run = runs[last_target_idx + 1] if last_target_idx + 1 < len(runs) else None
            for r in target_runs:
                p.remove(r)
            if next_run is not None:
                # addprevious on a fixed anchor: each call lands immediately
                # before it, so iterate in forward order to keep new_runs in sequence.
                for nr in new_runs:
                    next_run.addprevious(nr)
            else:
                for nr in new_runs:
                    p.append(nr)

    # --- Phase 2: Process cross-reference sentinels in all paragraphs ---
    # Iterate raw w:p elements so paragraphs inside lxml-built figure tables
    # (not enumerated by python-docx's doc.tables) are also processed.
    for p in all_p_els:
        run_queue = collections.deque(p.findall(f'{{{W}}}r'))
        while run_queue:
            run = run_queue.popleft()
            for t_el in run.findall(f'{{{W}}}t'):
                txt = t_el.text or ''

                # --- Heading bookmark: @@SECLABEL:id@@ ---
                lm = _RE_SECLABEL.search(txt)
                if lm:
                    sec_id = lm.group(1)
                    bm_name = _safe_bm_name(sec_id)
                    bid = bookmark_counter[0]
                    bookmark_counter[0] += 1

                    # Strip sentinel from the run text
                    t_el.text = txt[:lm.start()] + txt[lm.end():]

                    bm_start = OxmlElement('w:bookmarkStart')
                    bm_start.set(qn('w:id'), str(bid))
                    bm_start.set(qn('w:name'), bm_name)
                    run.addprevious(bm_start)

                    bm_end = OxmlElement('w:bookmarkEnd')
                    bm_end.set(qn('w:id'), str(bid))
                    run.addnext(bm_end)

                    replaced_labels += 1
                    continue  # a run carries at most one sentinel

                # --- Section cross-reference field: @@SECREF:id@@ ---
                rm = _RE_SECREF_SENT.search(txt)
                if rm:
                    ref_id = rm.group(1)
                    bm_name = _safe_bm_name(ref_id)

                    before_txt = txt[:rm.start()]
                    after_txt  = txt[rm.end():]

                    # Emit a native Word REF field with \n (paragraph number)
                    # and \h (hyperlink).  "Section " is static text before the
                    # field; the REF generates the heading number from Word's
                    # heading style numbering.  No custom numbering needed.
                    tail_elements = [
                        _text_run('Section ', source_run=run),
                        _fld_run('begin'),
                        _instr_run(f' REF "{bm_name}" \\n \\h '),
                        _fld_run('separate'),
                        _text_run('?', source_run=run),
                        _fld_run('end'),
                    ]
                    after_run = None
                    if after_txt:
                        after_run = _text_run(after_txt, source_run=run)
                        tail_elements.append(after_run)

                    for el in reversed(tail_elements):
                        run.addnext(el)

                    if after_run is not None:
                        run_queue.appendleft(after_run)  # process remaining sentinels

                    # Keep before-text in the current run, or clear it if empty
                    t_el.text = before_txt if before_txt else ''

                    replaced_refs += 1
                    continue

                # --- Figure cross-reference field: @@FIGREF:id@@ ---
                fm = _RE_FIGREF_SENT.search(txt)
                if fm:
                    fig_id = fm.group(1)
                    bm_name = _safe_fig_bm_name(fig_id)
                    fig_num = fig_map.get(fig_id)
                    display = f'Figure {fig_num}' if fig_num else f'[?{fig_id}]'

                    before_txt = txt[:fm.start()]
                    after_txt  = txt[fm.end():]

                    # REF field with \h switch (hyperlink) and \* MERGEFORMAT.
                    # The REF \h bookmark creates a clickable hyperlink to the figure.
                    # We use a static display string so F9 doesn't change it.
                    tail_elements = [
                        _fld_run('begin'),
                        _instr_run(f' REF "{bm_name}" \\h'),
                        _fld_run('separate'),
                        _text_run(display, source_run=run),
                        _fld_run('end'),
                    ]
                    after_run = None
                    if after_txt:
                        after_run = _text_run(after_txt, source_run=run)
                        tail_elements.append(after_run)

                    for el in reversed(tail_elements):
                        run.addnext(el)

                    if after_run is not None:
                        run_queue.appendleft(after_run)

                    if before_txt:
                        t_el.text = before_txt
                    else:
                        p.remove(run)

                    replaced_fig_refs += 1

                # --- Table cross-reference field: @@TABREF:id@@ ---
                tm = _RE_TABREF_SENT.search(txt)
                if tm:
                    tab_id = tm.group(1)
                    bm_name = _safe_tab_bm_name(tab_id)
                    tab_num = tab_map.get(tab_id)
                    display = f'Table {tab_num}' if tab_num else f'[?{tab_id}]'

                    before_txt = txt[:tm.start()]
                    after_txt  = txt[tm.end():]

                    tail_elements = [
                        _fld_run('begin'),
                        _instr_run(f' REF "{bm_name}" \\h'),
                        _fld_run('separate'),
                        _text_run(display, source_run=run),
                        _fld_run('end'),
                    ]
                    after_run = None
                    if after_txt:
                        after_run = _text_run(after_txt, source_run=run)
                        tail_elements.append(after_run)

                    for el in reversed(tail_elements):
                        run.addnext(el)

                    if after_run is not None:
                        run_queue.appendleft(after_run)

                    if before_txt:
                        t_el.text = before_txt
                    else:
                        p.remove(run)

                    replaced_tab_refs += 1

    if replaced_labels or replaced_refs or replaced_fig_refs or replaced_tab_refs:
        doc.save(docx_path)
        print(f'  Post-processed {replaced_labels} bookmark(s), {replaced_refs} section ref(s), '
              f'{replaced_fig_refs} figure ref(s), {replaced_tab_refs} table ref(s)')


def _post_process_image_wrapping(docx_path: str) -> None:
    """Replace wp:inline image elements with wp:anchor (Top and Bottom wrapping)."""
    from docx import Document as DocxDoc

    doc = DocxDoc(docx_path)
    WP = _NS_WP
    inlines = list(doc.element.body.findall(f'.//{{{WP}}}inline'))
    if not inlines:
        return
    for el in inlines:
        _inline_to_anchor(el)
    doc.save(docx_path)
    print(f'Post-processed {len(inlines)} image(s) → Top and Bottom wrapping in {docx_path}')


def _validate_template_context(tpl: DocxTemplate, context: dict) -> None:
    """Validate that template Jinja variables have corresponding context keys.

    Uses docxtpl's get_undeclared_template_variables() (jinja2's own AST
    analysis), which sees every variable reference — including ones split
    across Word runs or used in filters/conditions — and correctly excludes
    loop-local variables.  Checks both directions against the context dict.

    Raises SystemExit on mismatch.
    """
    template_vars = tpl.get_undeclared_template_variables()
    context_keys = set(context.keys())

    errors = []

    # 1. Every template variable must have a context key
    for var in sorted(template_vars):
        if var not in context_keys:
            errors.append(f'Template variable "{var}" not found in context')

    # 2. Every context key must be used by the template
    for key in sorted(context_keys):
        if key not in template_vars:
            errors.append(f'Context key "{key}" not used in template')

    if errors:
        print('\nTemplate-context mismatch:')
        for e in errors:
            print(f'  {e}')
        raise SystemExit(1)


def render(
    template_path: str,
    context: dict,
    body_var_name: str | list[str],
    output_path: str,
    image_base: str = '.',
    figure_title_style: str = 'FImageTitle',
) -> None:
    """Render the instrumented template with a context dict and write to output_path.

    Args:
        template_path: Path to the Jinja-instrumented DOCX (from the project's
                       template prep script).
        context:       Context dict (from the VAR blocks + parsed body).
        body_var_name: Key(s) in context holding ContentNode lists. A single
                       name for the common one-freeform-VAR template; a list
                       of names for a fixed-structure template with multiple
                       independent content loops (see the jinjify-template
                       skill). All lists are concatenated before figure/table
                       numbering and math/inline-run sentinel assignment so
                       numbering and cross-references stay consistent across
                       the whole document, then split back apart so each VAR
                       renders through its own template loop.
        output_path:   Destination DOCX file.
        image_base:    Directory to search for figure image files.
        figure_title_style:
                       Template style ID for figure title paragraphs; the
                       figure/cross-ref post-processing keys on it.  Projects
                       override it via RENDER_OPTIONS in their prep script.
    """
    tpl = DocxTemplate(template_path)
    img_base = Path(image_base)

    sec = Document(template_path).sections[0]
    text_width = sec.page_width - sec.left_margin - sec.right_margin

    body_var_names = [body_var_name] if isinstance(body_var_name, str) else list(body_var_name)

    # Concatenate every freeform VAR's content nodes so figure/table numbers
    # and math/inline sentinels are assigned once, globally, in draft order —
    # not reset to zero (and colliding) at each VAR's boundary.
    content_nodes: list[ContentNode] = []
    boundaries: list[tuple[str, int]] = []
    for name in body_var_names:
        nodes = context[name]
        content_nodes.extend(nodes)
        boundaries.append((name, len(nodes)))

    # Finalize: assign sequential figure/table numbers, build maps
    figures_list, tables_list, fig_map, tab_map = finalize_content(content_nodes)

    # Build content proxy list (assigns math counters)
    content_proxies, inline_map = _build_content_proxies(content_nodes, tpl, img_base, text_width)

    # Split proxies back into each VAR's own list, in the template's context
    offset = 0
    for name, length in boundaries:
        context[name] = content_proxies[offset:offset + length]
        offset += length

    _validate_template_context(tpl, context)

    tpl.render(context)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    tpl.save(output_path)

    # Post-process: replace TABLE_PLACEHOLDER_N paragraphs with real tables
    _post_process_tables(output_path, tables_list)
    # Post-process: restore inline bold/italic runs for headings/paragraphs/bullets
    _post_process_inline_runs(output_path, inline_map)
    # Post-process: wrap figure blocks in borderless 2-row tables
    _post_process_figures(output_path, figure_title_style)
    # Post-process: replace MATH_DISP_N / MATH_PARA_N sentinels with OMML
    _post_process_math(output_path, content_proxies)
    # Post-process: insert Word bookmarks and REF fields for section cross-references
    _post_process_crossrefs(output_path, content_nodes, fig_map, tab_map,
                            figure_title_style)
    # Post-process: convert inline images to Top and Bottom wrapping
    _post_process_image_wrapping(output_path)
    print(f'Rendered → {output_path}')
